### ISSUE TITLE
install fails on Windows 7

### ISSUE THREAD

**Issue by PavelKotov1** [unipacker/unipacker#24]
Hello!
Seems like I am following installation instructions to the letter, but install still fails with this error:
ERROR: Command "'c:\program files (x86)\python37-32\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'D:\\cygwin64\\tmp\\pip-install-wb408v9s\\unicorn-unipacker\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'D:\cygwin64\tmp\pip-record-t15lv_bc\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in D:\cygwin64\tmp\pip-install-wb408v9s\unicorn-unipacker\

Could somebody please help? Thanks in advance!

**Comment by Masrepus** [comment]
It happens because our unicorn-engine fork somehow won't compile on Windows. This is a known issue, but we currently do not have access to a Windows machine for thorough debugging. We tried to create a precompiled pypi package for Windows, but at the moment only the Linux and Mac builds work on our CI platform. We will continue investigating Windows builds, but for the moment I would suggest to use the Docker version if you are on Windows. I think this should work without further problems. Otherwise you could try using Unipacker in Windows Subsystem for Linux

**Comment by PavelKotov1** [comment]
Tried it on Debian, worked like magic!
Thanks for the great tool!
Kind Regards, pk

**Comment by Masrepus** [comment]
Thanks! I'm glad it works for you now!

**Comment by Masrepus** [comment]
Just a quick heads up: We are now using a new unicorn engine version which fixes the Windows build. Installing unipacker on Windows should thus work now.
