### ISSUE TITLE
AttributeError: 'Shell' object has no attribute 'shell_event'

### ISSUE THREAD

**Issue by esmailzadeh1** [unipacker/unipacker#41]
Hi,

I am going to use your software to uncompress the upx file. But this error is received:

`Enter the option ID: 0
Please enter the sample path (single file or directory): /usr/bin/uname.upx
e_magic = 17791
Wrong DOS Magic Value (MZ). Aborting...
Could not initialize /usr/bin/uname.upx: 
Traceback (most recent call last):
  File "/usr/local/bin/unipacker", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/unipacker/shell.py", line 742, in main
    Shell()
  File "/usr/local/lib/python3.6/site-packages/unipacker/shell.py", line 82, in __init__
    self.shell_event.wait()
AttributeError: 'Shell' object has no attribute 'shell_event'
`

what is the reason?

Thank you.

**Comment by Masrepus** [comment]
Could you share the sample you would like to unpack or is this not possible?

**Comment by esmailzadeh1** [comment]
> Could you share the sample you would like to unpack or is this not possible?

I compress a sample file (/usr/bin/uname) with upx -o /usr/bin/uname.upx /usr/bin/uname  and enter it as file in unipacker.

centos 7 64bit
Python 3.6.8

Thank you.

**Comment by Masrepus** [comment]
Ah I see. The principal problem we have here is that our unpacker is targeted towards Windows executables. Generally speaking, it would be possible to also unpack Linux executables using emulation techniques, but this needs some major extensions to unipacker. So in order to try our UPX unpacking module, you should use UPX on a Windows system, e.g. a VM, pack a file of your choice, and then you can come back to your CentOS system and use unipacker to unpack the file.

On the other hand, unipacker should of course not crash if a Linux sample has been provided, so thank you for notifying us of this!
