### ISSUE TITLE
init_uc can take a long time

### ISSUE THREAD

**Issue by steven-hh-ding** [unipacker/unipacker#47]
Hello!

https://github.com/unipacker/unipacker/blob/37724cc8323b06fbe3f0864a8954704b2a2e1c4a/unipacker/core.py#L152-L155

In our test, init_uc can take a really long time for certain file that is intentionally made large e.g.
https://bazaar.abuse.ch/sample/c92af6007b3c7f48e9c18d73dd99d889dd08dbccfe12c346724a149ba483ec2c/ 

So we can't set timeout on this function. Can we move the call for `init_uc`  to `engine.emu` ?

**Comment by Masrepus** [comment]
Unfortunately that can't easily be moved, as the interactive shell can only start once the unicorn engine has been initialized. This is because otherwise we can't give the user the option to do basically anything before starting the emulation, like inspecting/modifying registers and memory.
Without having tried it yet, I suspect the main part that takes a long time is the pefile loading, as we have already seen several samples that pefile can't handle quickly or even at all. Having a custom PE loader that is more robust has already been on our roadmap for quite some time, but until we have this, I think there is no real way around this issue rather than maybe using a new thread when you create the UnpackerEngine object.
